name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_11ba3dfb-e3fc-4e9b-86e7-3f2a920040b2 }}
          wangtao: ${{ secrets.X9949727 }}
          # 时间线
          SHOW_LOC_CHART: False
